"use client";
import { useApp } from "@/lib/app-context";
import { CountUp } from "@/components/count-up";

export function HomeScreen() {
  const v = useApp();
  return (
    <div data-screen-label="首页 仪表盘" className="bo-enter" style={{ maxWidth: '1440px', margin: '0 auto' }}>
      <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', gap: '20px', marginBottom: '24px', flexWrap: 'wrap' }}>
        <div>
          <div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', letterSpacing: '.14em', color: 'var(--pri)', fontWeight: 600, marginBottom: '10px' }}>// 仪表盘 · OVERVIEW</div>
          <div style={{ fontFamily: "'Space Grotesk','Noto Sans SC',sans-serif", fontSize: '26px', fontWeight: 700, color: 'var(--ink)', letterSpacing: '-.01em' }}>早上好，前端追梦人</div>
          <div style={{ fontSize: '13.5px', color: 'var(--ink2)', marginTop: '8px' }}>距离下次面试还有 <span style={{ fontFamily: "'JetBrains Mono',monospace", color: 'var(--pri)', fontWeight: 700 }}>07</span> 天 · 今日已完成 <span style={{ fontFamily: "'JetBrains Mono',monospace", fontWeight: 700 }}>56</span> 题，保持节奏。</div>
        </div>
        <div style={{ display: 'flex', gap: '10px' }}>
          <button style={{ background: 'var(--pri)', border: '1px solid var(--pri)', color: '#fff', borderRadius: '8px', padding: '10px 18px', fontSize: '13.5px', fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit', display: 'flex', alignItems: 'center', gap: '8px', whiteSpace: 'nowrap', boxShadow: '0 6px 16px rgba(45,91,255,.24)' }} onClick={v.nav.practice.go}>继续刷题<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h13M13 6l6 6-6 6" /></svg></button>
        </div>
      </div>

      {/* KPI ROW */}
      <div className="bo-stagger" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(202px,1fr))', gap: '14px', marginBottom: '26px' }}>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '12px', padding: '17px 18px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><span style={{ fontSize: '12.5px', color: 'var(--ink3)', fontWeight: 600 }}>题库总数</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--ink3)" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" style={{ opacity: .6 }}><path d="M6 4h11a2 2 0 0 1 2 2v14H8a2 2 0 0 1-2-2z" /><path d="M6 4a2 2 0 0 0-2 2v12a2 2 0 0 1 2-2h13" /></svg></div>
          <div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '30px', fontWeight: 700, color: 'var(--ink)', letterSpacing: '-.02em', lineHeight: 1, marginTop: '13px' }}><CountUp to={8642} comma /></div>
          <div style={{ marginTop: '10px', fontSize: '12px', color: 'var(--ink3)', display: 'flex', alignItems: 'center', gap: '6px' }}><span style={{ fontFamily: "'JetBrains Mono',monospace", color: '#0E9F6E', fontWeight: 700 }}>+120</span>较昨日</div>
        </div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '12px', padding: '17px 18px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><span style={{ fontSize: '12.5px', color: 'var(--ink3)', fontWeight: 600 }}>今日完成</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--ink3)" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" style={{ opacity: .6 }}><rect x="4" y="4" width="16" height="16" rx="3" /><path d="M8.5 12l2.4 2.4L15.5 9.5" /></svg></div>
          <div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '30px', fontWeight: 700, color: 'var(--ink)', letterSpacing: '-.02em', lineHeight: 1, marginTop: '13px' }}><CountUp to={56} /></div>
          <div style={{ marginTop: '10px', fontSize: '12px', color: 'var(--ink3)', display: 'flex', alignItems: 'center', gap: '6px' }}><span style={{ fontFamily: "'JetBrains Mono',monospace", color: '#0E9F6E', fontWeight: 700 }}>+18</span>较昨日</div>
        </div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '12px', padding: '17px 18px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><span style={{ fontSize: '12.5px', color: 'var(--ink3)', fontWeight: 600 }}>正确率</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--ink3)" strokeWidth="1.7" style={{ opacity: .6 }}><circle cx="12" cy="12" r="8" /><circle cx="12" cy="12" r="3.2" /></svg></div>
          <div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '30px', fontWeight: 700, color: 'var(--ink)', letterSpacing: '-.02em', lineHeight: 1, marginTop: '13px' }}><CountUp to={76.8} dec={1} /><span style={{ fontSize: '18px', color: 'var(--ink3)' }}>%</span></div>
          <div style={{ marginTop: '10px', fontSize: '12px', color: 'var(--ink3)', display: 'flex', alignItems: 'center', gap: '6px' }}><span style={{ fontFamily: "'JetBrains Mono',monospace", color: '#0E9F6E', fontWeight: 700 }}>+6.3%</span>较昨日</div>
        </div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '12px', padding: '17px 18px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><span style={{ fontSize: '12.5px', color: 'var(--ink3)', fontWeight: 600 }}>连续打卡</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--ink3)" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" style={{ opacity: .6 }}><path d="M13 3L6 13h5l-1 8 7-11h-5z" /></svg></div>
          <div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '30px', fontWeight: 700, color: 'var(--ink)', letterSpacing: '-.02em', lineHeight: 1, marginTop: '13px' }}><CountUp to={18} /><span style={{ fontSize: '15px', color: 'var(--ink3)', fontWeight: 500 }}> 天</span></div>
          <div style={{ marginTop: '10px', fontSize: '12px', color: 'var(--ink3)', display: 'flex', alignItems: 'center', gap: '6px' }}>累计打卡 <span style={{ fontFamily: "'JetBrains Mono',monospace", color: 'var(--ink2)', fontWeight: 700 }}>62</span> 天</div>
        </div>
      </div>

      {/* CATEGORIES */}
      <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', marginBottom: '14px' }}>
        <div>
          <div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', letterSpacing: '.13em', color: 'var(--ink3)', fontWeight: 600, marginBottom: '6px' }}>// CATEGORIES</div>
          <div style={{ fontFamily: "'Space Grotesk','Noto Sans SC',sans-serif", fontSize: '16px', fontWeight: 700, color: 'var(--ink)' }}>分类练习进度</div>
        </div>
        <div style={{ fontSize: '12.5px', color: 'var(--pri)', fontWeight: 600, cursor: 'pointer', fontFamily: "'Noto Sans SC'" }}>全部 10 类 →</div>
      </div>
      <div className="bo-stagger" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(214px,1fr))', gap: '14px', marginBottom: '26px' }}>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '11px', padding: '13px 14px 0', overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'JetBrains Mono',monospace", fontWeight: 700, fontSize: '12px', color: 'var(--ink)' }}>&lt;/&gt;</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>HTML</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '12px', color: 'var(--ink2)', fontWeight: 600 }}>85%</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', margin: '9px 0 12px' }}>812 题</div><div style={{ height: '3px', margin: '0 -14px', background: 'var(--track)' }}><div style={{ width: '85%', height: '100%', background: 'var(--pri)', transformOrigin: 'left center', animation: 'boGrowX .9s cubic-bezier(.22,.61,.36,1) both' }}></div></div></div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '11px', padding: '13px 14px 0', overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'JetBrains Mono',monospace", fontWeight: 700, fontSize: '12px', color: 'var(--ink)' }}>#</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>CSS</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '12px', color: 'var(--ink2)', fontWeight: 600 }}>72%</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', margin: '9px 0 12px' }}>768 题</div><div style={{ height: '3px', margin: '0 -14px', background: 'var(--track)' }}><div style={{ width: '72%', height: '100%', background: 'var(--pri)', transformOrigin: 'left center', animation: 'boGrowX .9s cubic-bezier(.22,.61,.36,1) both' }}></div></div></div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '11px', padding: '13px 14px 0', overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'JetBrains Mono',monospace", fontWeight: 700, fontSize: '12px', color: 'var(--ink)' }}>JS</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>JavaScript</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '12px', color: 'var(--ink2)', fontWeight: 600 }}>68%</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', margin: '9px 0 12px' }}>1,352 题</div><div style={{ height: '3px', margin: '0 -14px', background: 'var(--track)' }}><div style={{ width: '68%', height: '100%', background: 'var(--pri)', transformOrigin: 'left center', animation: 'boGrowX .9s cubic-bezier(.22,.61,.36,1) both' }}></div></div></div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '11px', padding: '13px 14px 0', overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'JetBrains Mono',monospace", fontWeight: 700, fontSize: '12px', color: 'var(--ink)' }}>TS</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>TypeScript</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '12px', color: 'var(--ink2)', fontWeight: 600 }}>61%</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', margin: '9px 0 12px' }}>642 题</div><div style={{ height: '3px', margin: '0 -14px', background: 'var(--track)' }}><div style={{ width: '61%', height: '100%', background: 'var(--pri)', transformOrigin: 'left center', animation: 'boGrowX .9s cubic-bezier(.22,.61,.36,1) both' }}></div></div></div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '11px', padding: '13px 14px 0', overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'JetBrains Mono',monospace", fontWeight: 700, fontSize: '11px', color: 'var(--ink)' }}>Re</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>React</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '12px', color: 'var(--ink2)', fontWeight: 600 }}>73%</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', margin: '9px 0 12px' }}>1,102 题</div><div style={{ height: '3px', margin: '0 -14px', background: 'var(--track)' }}><div style={{ width: '73%', height: '100%', background: 'var(--pri)', transformOrigin: 'left center', animation: 'boGrowX .9s cubic-bezier(.22,.61,.36,1) both' }}></div></div></div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '11px', padding: '13px 14px 0', overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'JetBrains Mono',monospace", fontWeight: 700, fontSize: '12px', color: 'var(--ink)' }}>Vu</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>Vue</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '12px', color: 'var(--ink2)', fontWeight: 600 }}>69%</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', margin: '9px 0 12px' }}>856 题</div><div style={{ height: '3px', margin: '0 -14px', background: 'var(--track)' }}><div style={{ width: '69%', height: '100%', background: 'var(--pri)', transformOrigin: 'left center', animation: 'boGrowX .9s cubic-bezier(.22,.61,.36,1) both' }}></div></div></div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '11px', padding: '13px 14px 0', overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--ink2)' }}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><circle cx="12" cy="12" r="8" /><path d="M4 12h16M12 4c2.4 2.5 2.4 13 0 16M12 4c-2.4 2.5-2.4 13 0 16" strokeLinecap="round" /></svg></div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>浏览器</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '12px', color: 'var(--ink2)', fontWeight: 600 }}>58%</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', margin: '9px 0 12px' }}>612 题</div><div style={{ height: '3px', margin: '0 -14px', background: 'var(--track)' }}><div style={{ width: '58%', height: '100%', background: 'var(--pri)', transformOrigin: 'left center', animation: 'boGrowX .9s cubic-bezier(.22,.61,.36,1) both' }}></div></div></div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '11px', padding: '13px 14px 0', overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--ink2)' }}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="5" r="2.2" /><circle cx="5" cy="18" r="2.2" /><circle cx="19" cy="18" r="2.2" /><path d="M12 7.2v3.3M10.5 12l-4 4M13.5 12l4 4" /></svg></div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>网络</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '12px', color: 'var(--ink2)', fontWeight: 600 }}>66%</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', margin: '9px 0 12px' }}>845 题</div><div style={{ height: '3px', margin: '0 -14px', background: 'var(--track)' }}><div style={{ width: '66%', height: '100%', background: 'var(--pri)', transformOrigin: 'left center', animation: 'boGrowX .9s cubic-bezier(.22,.61,.36,1) both' }}></div></div></div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '11px', padding: '13px 14px 0', overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--ink2)' }}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l8 4.5v9L12 21l-8-4.5v-9z" /><path d="M4 7.5l8 4.5 8-4.5M12 12v9" /></svg></div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>工程化</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '12px', color: 'var(--ink2)', fontWeight: 600 }}>55%</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', margin: '9px 0 12px' }}>438 题</div><div style={{ height: '3px', margin: '0 -14px', background: 'var(--track)' }}><div style={{ width: '55%', height: '100%', background: 'var(--pri)', transformOrigin: 'left center', animation: 'boGrowX .9s cubic-bezier(.22,.61,.36,1) both' }}></div></div></div>
        <div className="bo-card" style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '11px', padding: '13px 14px 0', overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--ink2)' }}><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><circle cx="7" cy="6" r="2.1" /><circle cx="7" cy="18" r="2.1" /><circle cx="17" cy="12" r="2.1" /><path d="M9 6h4a2 2 0 0 1 2 2v2M9 18h4a2 2 0 0 0 2-2v-2M7 8v8" /></svg></div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>算法</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '12px', color: 'var(--ink2)', fontWeight: 600 }}>60%</div></div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', margin: '9px 0 12px' }}>1,213 题</div><div style={{ height: '3px', margin: '0 -14px', background: 'var(--track)' }}><div style={{ width: '60%', height: '100%', background: 'var(--pri)', transformOrigin: 'left center', animation: 'boGrowX .9s cubic-bezier(.22,.61,.36,1) both' }}></div></div></div>
      </div>

      {/* RECENT + TREND */}
      <div className="bo-col2" style={{ display: 'grid', gridTemplateColumns: 'minmax(0,5fr) minmax(0,7fr)', gap: '16px', alignItems: 'start' }}>
        <div style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '12px', padding: '18px 20px' }}>
          <div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', letterSpacing: '.13em', color: 'var(--ink3)', fontWeight: 600, marginBottom: '5px' }}>// RECENT</div>
          <div style={{ fontFamily: "'Space Grotesk','Noto Sans SC',sans-serif", fontSize: '16px', fontWeight: 700, color: 'var(--ink)', marginBottom: '6px' }}>最近练习</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '13px 0', borderBottom: '1px solid var(--divider)' }}>
            <div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'JetBrains Mono',monospace", fontWeight: 700, fontSize: '11px', color: 'var(--ink)' }}>JS</div>
            <div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>JavaScript 作用域和闭包</div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', marginTop: '3px' }}>ACC 80% · 6m12s</div></div>
            <span style={{ display: 'inline-flex', alignItems: 'center', gap: '5px', border: '1px solid var(--line)', borderRadius: '6px', padding: '3px 8px', fontSize: '11px', fontWeight: 600, color: '#B7791F' }}><span style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#F79009' }}></span>中等</span>
            <span style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', width: '42px', textAlign: 'right' }}>10:23</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '13px 0', borderBottom: '1px solid var(--divider)' }}>
            <div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'JetBrains Mono',monospace", fontWeight: 700, fontSize: '12px', color: 'var(--ink)' }}>#</div>
            <div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>CSS 盒模型的宽度计算</div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', marginTop: '3px' }}>ACC 100% · 2m05s</div></div>
            <span style={{ display: 'inline-flex', alignItems: 'center', gap: '5px', border: '1px solid var(--line)', borderRadius: '6px', padding: '3px 8px', fontSize: '11px', fontWeight: 600, color: '#0E9F6E' }}><span style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#12B76A' }}></span>简单</span>
            <span style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', width: '42px', textAlign: 'right' }}>09:41</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '13px 0' }}>
            <div style={{ width: '32px', height: '32px', flex: 'none', border: '1px solid var(--line)', borderRadius: '8px', background: 'var(--surface-3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'JetBrains Mono',monospace", fontWeight: 700, fontSize: '12px', color: 'var(--ink)' }}>Vu</div>
            <div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: '13.5px', fontWeight: 600, color: 'var(--ink)' }}>Vue 响应式原理与依赖收集</div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', marginTop: '3px' }}>ACC 67% · 8m40s</div></div>
            <span style={{ display: 'inline-flex', alignItems: 'center', gap: '5px', border: '1px solid var(--line)', borderRadius: '6px', padding: '3px 8px', fontSize: '11px', fontWeight: 600, color: '#D63C31' }}><span style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#F04438' }}></span>困难</span>
            <span style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink3)', width: '42px', textAlign: 'right' }}>21:15</span>
          </div>
        </div>

        <div style={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: '12px', padding: '18px 20px' }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '8px' }}>
            <div><div style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', letterSpacing: '.13em', color: 'var(--ink3)', fontWeight: 600, marginBottom: '5px' }}>// WEEKLY</div><div style={{ fontFamily: "'Space Grotesk','Noto Sans SC',sans-serif", fontSize: '16px', fontWeight: 700, color: 'var(--ink)' }}>本周学习趋势</div></div>
            <div style={{ display: 'flex', gap: '14px', paddingTop: '4px' }}>
              <span style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink2)' }}><span style={{ width: '11px', height: '3px', borderRadius: '2px', background: 'var(--pri)' }}></span>题量</span>
              <span style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: "'JetBrains Mono',monospace", fontSize: '11px', color: 'var(--ink2)' }}><span style={{ width: '11px', height: '3px', borderRadius: '2px', background: '#BFC9DC' }}></span>正确率</span>
            </div>
          </div>
          <svg viewBox="0 0 640 224" style={{ width: '100%', height: 'auto', display: 'block' }}>
            <line x1="54" y1="18" x2="628" y2="18" stroke="rgba(20,26,45,.05)" strokeWidth="1" />
            <line x1="54" y1="74.7" x2="628" y2="74.7" stroke="rgba(20,26,45,.05)" strokeWidth="1" />
            <line x1="54" y1="131.3" x2="628" y2="131.3" stroke="rgba(20,26,45,.05)" strokeWidth="1" />
            <line x1="54" y1="188" x2="628" y2="188" stroke="rgba(20,26,45,.09)" strokeWidth="1" />
            <text x="44" y="22" textAnchor="end" fill="#AEB6C2" fontSize="10.5" fontFamily="'JetBrains Mono',monospace">90</text>
            <text x="44" y="78.7" textAnchor="end" fill="#AEB6C2" fontSize="10.5" fontFamily="'JetBrains Mono',monospace">60</text>
            <text x="44" y="135.3" textAnchor="end" fill="#AEB6C2" fontSize="10.5" fontFamily="'JetBrains Mono',monospace">30</text>
            <text x="44" y="192" textAnchor="end" fill="#AEB6C2" fontSize="10.5" fontFamily="'JetBrains Mono',monospace">0</text>
            <path d="M62.0,138.9 L155.7,86.0 L249.3,104.9 L343.0,112.4 L436.7,78.4 L530.3,93.6 L624.0,52.0 L624.0,188 L62.0,188 Z" fill="var(--pri)" opacity="0.06" />
            <polyline points="62.0,157.8 155.7,123.8 249.3,131.3 343.0,142.7 436.7,112.4 530.3,108.7 624.0,86.0" fill="none" stroke="#BFC9DC" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
            <polyline points="62.0,138.9 155.7,86.0 249.3,104.9 343.0,112.4 436.7,78.4 530.3,93.6 624.0,52.0" fill="none" stroke="var(--pri)" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" style={{ strokeDasharray: 1600, strokeDashoffset: 1600, animation: 'boDraw 1.6s ease .3s both' }} />
            <circle cx="62.0" cy="138.9" r="3.2" fill="#fff" stroke="var(--pri)" strokeWidth="2" /><circle cx="155.7" cy="86.0" r="3.2" fill="#fff" stroke="var(--pri)" strokeWidth="2" /><circle cx="249.3" cy="104.9" r="3.2" fill="#fff" stroke="var(--pri)" strokeWidth="2" /><circle cx="343.0" cy="112.4" r="3.2" fill="#fff" stroke="var(--pri)" strokeWidth="2" /><circle cx="436.7" cy="78.4" r="3.2" fill="#fff" stroke="var(--pri)" strokeWidth="2" /><circle cx="530.3" cy="93.6" r="3.2" fill="#fff" stroke="var(--pri)" strokeWidth="2" /><circle cx="624.0" cy="52.0" r="4.4" fill="var(--pri)" stroke="#fff" strokeWidth="2.2" />
            <text x="62" y="210" textAnchor="middle" fill="#9AA3B2" fontSize="11" fontFamily="'JetBrains Mono',monospace">5/14</text><text x="155.7" y="210" textAnchor="middle" fill="#9AA3B2" fontSize="11" fontFamily="'JetBrains Mono',monospace">5/15</text><text x="249.3" y="210" textAnchor="middle" fill="#9AA3B2" fontSize="11" fontFamily="'JetBrains Mono',monospace">5/16</text><text x="343" y="210" textAnchor="middle" fill="#9AA3B2" fontSize="11" fontFamily="'JetBrains Mono',monospace">5/17</text><text x="436.7" y="210" textAnchor="middle" fill="#9AA3B2" fontSize="11" fontFamily="'JetBrains Mono',monospace">5/18</text><text x="530.3" y="210" textAnchor="middle" fill="#9AA3B2" fontSize="11" fontFamily="'JetBrains Mono',monospace">5/19</text><text x="624" y="210" textAnchor="middle" fill="#9AA3B2" fontSize="11" fontFamily="'JetBrains Mono',monospace">5/20</text>
          </svg>
        </div>
      </div>
    </div>
  );
}
